local M = {}

function M.build(variant, opts)
  opts = opts or {}
  local p = require("solarized-duo.palette")
  local s = p.solarized
  local v = variant == "dark" and p.darcula or p.lightcula

  local bg      = opts.transparent and "NONE" or v.bg
  local bg_alt  = opts.transparent and "NONE" or v.bg_alt
  local bg_sign = opts.transparent and "NONE" or v.bg
  local bg_hl   = v.bg_hl

  local hl = {
    Normal       = { fg = v.fg, bg = bg },
    NormalNC     = { fg = v.fg, bg = bg },
    NormalFloat  = { fg = v.fg, bg = bg_alt },
    FloatBorder  = { fg = v.border, bg = bg_alt },
    FloatTitle   = { fg = s.blue, bg = bg_alt, bold = true },

    Cursor       = { fg = v.bg, bg = v.cursor },
    CursorLine   = { bg = bg_hl },
    CursorLineNr = { fg = s.yellow, bg = "NONE", bold = true },
    CursorColumn = { bg = bg_hl },
    ColorColumn  = { bg = bg_hl },

    LineNr       = { fg = v.line_nr, bg = "NONE" },
    LineNrAbove  = { fg = v.line_nr, bg = "NONE" },
    LineNrBelow  = { fg = v.line_nr, bg = "NONE" },
    SignColumn   = { fg = v.gutter, bg = "NONE" },
    VertSplit    = { fg = v.border, bg = bg },
    WinSeparator = { fg = v.border, bg = bg },
    Folded       = { fg = v.fg_dim, bg = bg_alt },
    FoldColumn   = { fg = v.gutter, bg = bg },
    EndOfBuffer  = { fg = "bg", bg = "NONE" },

    Visual       = { bg = v.bg_sel },
    VisualNOS    = { bg = v.bg_sel },
    Search       = { fg = v.bg, bg = s.yellow },
    IncSearch    = { fg = v.bg, bg = s.orange },
    CurSearch    = { fg = v.bg, bg = s.orange, bold = true },
    MatchParen   = { fg = s.magenta, bold = true, underline = true },

    Pmenu        = { fg = v.fg, bg = bg_alt },
    PmenuSel     = { fg = v.fg, bg = v.bg_sel, bold = true },
    PmenuSbar    = { bg = bg_alt },
    PmenuThumb   = { bg = v.border },

    StatusLine   = { fg = v.fg, bg = v.bg_alt },
    StatusLineNC = { fg = v.fg_dim, bg = v.bg_alt },
    TabLine      = { fg = v.fg_dim, bg = v.bg_alt },
    TabLineFill  = { bg = v.bg_alt },
    TabLineSel   = { fg = v.fg, bg = bg, bold = true },
    WinBar       = { fg = v.fg, bg = bg },
    WinBarNC     = { fg = v.fg_dim, bg = bg },

    ErrorMsg     = { fg = s.red, bold = true },
    WarningMsg   = { fg = s.yellow, bold = true },
    ModeMsg      = { fg = s.blue, bold = true },
    MoreMsg      = { fg = s.green, bold = true },
    Question     = { fg = s.cyan },
    Title        = { fg = s.orange, bold = true },
    Directory    = { fg = s.blue },
    NonText      = { fg = v.border },
    Whitespace   = { fg = v.border },
    SpecialKey   = { fg = v.border },

    Comment      = { fg = v.comment, italic = true },
    Constant     = { fg = s.cyan },
    String       = { fg = s.green },
    Character    = { fg = s.green },
    Number       = { fg = s.cyan },
    Boolean      = { fg = s.cyan },
    Float        = { fg = s.cyan },
    Identifier   = { fg = s.blue },
    Function     = { fg = s.blue, bold = true },
    Statement    = { fg = s.orange },
    Conditional  = { fg = s.orange },
    Repeat       = { fg = s.orange },
    Label        = { fg = s.orange },
    Operator     = { fg = s.violet },
    Keyword      = { fg = s.orange },
    Exception    = { fg = s.red },
    PreProc      = { fg = s.magenta },
    Include      = { fg = s.magenta },
    Define       = { fg = s.magenta },
    Macro        = { fg = s.magenta },
    Type         = { fg = s.yellow },
    StorageClass = { fg = s.yellow },
    Structure    = { fg = s.yellow },
    Typedef      = { fg = s.yellow },
    Special      = { fg = s.red },
    SpecialChar  = { fg = s.red },
    Delimiter    = { fg = v.fg },
    Tag          = { fg = s.blue },
    Underlined   = { fg = s.violet, underline = true },
    Todo         = { fg = s.magenta, bg = bg, bold = true },
    Error        = { fg = s.red, bold = true },

    DiffAdd      = { fg = s.green, bg = v.bg_alt },
    DiffChange   = { fg = s.yellow, bg = v.bg_alt },
    DiffDelete   = { fg = s.red, bg = v.bg_alt },
    DiffText     = { fg = s.blue, bg = v.bg_alt, bold = true },

    DiagnosticError = { fg = s.red },
    DiagnosticWarn  = { fg = s.yellow },
    DiagnosticInfo  = { fg = s.blue },
    DiagnosticHint  = { fg = s.cyan },
    DiagnosticOk    = { fg = s.green },
    DiagnosticUnderlineError = { sp = s.red, undercurl = true },
    DiagnosticUnderlineWarn  = { sp = s.yellow, undercurl = true },
    DiagnosticUnderlineInfo  = { sp = s.blue, undercurl = true },
    DiagnosticUnderlineHint  = { sp = s.cyan, undercurl = true },

    ["@variable"]          = { fg = v.fg },
    ["@variable.builtin"]  = { fg = s.red },
    ["@variable.parameter"] = { fg = s.violet },
    ["@variable.member"]   = { fg = s.blue },
    ["@property"]          = { fg = s.blue },
    ["@function"]          = { fg = s.blue, bold = true },
    ["@function.builtin"]  = { fg = s.cyan },
    ["@function.call"]     = { fg = s.blue },
    ["@method"]            = { fg = s.blue, bold = true },
    ["@constructor"]       = { fg = s.yellow },
    ["@keyword"]           = { fg = s.orange },
    ["@keyword.return"]    = { fg = s.red },
    ["@keyword.operator"]  = { fg = s.orange },
    ["@string"]            = { fg = s.green },
    ["@string.escape"]     = { fg = s.red },
    ["@number"]            = { fg = s.cyan },
    ["@boolean"]           = { fg = s.cyan },
    ["@type"]              = { fg = s.yellow },
    ["@type.builtin"]      = { fg = s.yellow },
    ["@comment"]           = { fg = v.comment, italic = true },
    ["@punctuation"]       = { fg = v.fg },
    ["@tag"]               = { fg = s.blue },
    ["@tag.attribute"]     = { fg = s.yellow },

    GitSignsAdd    = { fg = s.green, bg = bg_sign },
    GitSignsChange = { fg = s.yellow, bg = bg_sign },
    GitSignsDelete = { fg = s.red, bg = bg_sign },

    TelescopeNormal         = { fg = v.fg, bg = bg_alt },
    TelescopeBorder         = { fg = v.border, bg = bg_alt },
    TelescopeSelection      = { bg = v.bg_sel, bold = true },
    TelescopeSelectionCaret = { fg = s.orange, bg = v.bg_sel },
    TelescopeMultiSelection = { fg = s.yellow },
    TelescopeMultiIcon      = { fg = s.yellow },
    TelescopeMatching       = { fg = s.orange, bold = true },
    TelescopePromptPrefix   = { fg = s.blue, bg = bg_alt },
    TelescopePromptCounter  = { fg = v.fg_dim, bg = bg_alt },
    TelescopePromptNormal   = { fg = v.fg, bg = bg_alt },
    TelescopePromptBorder   = { fg = s.blue, bg = bg_alt },
    TelescopePromptTitle    = { fg = v.bg, bg = s.blue, bold = true },
    TelescopeResultsNormal  = { fg = v.fg, bg = bg_alt },
    TelescopeResultsBorder  = { fg = v.border, bg = bg_alt },
    TelescopeResultsTitle   = { fg = v.bg, bg = s.violet, bold = true },
    TelescopeResultsDiffAdd    = { fg = s.green },
    TelescopeResultsDiffChange = { fg = s.yellow },
    TelescopeResultsDiffDelete = { fg = s.red },
    TelescopePreviewNormal  = { fg = v.fg, bg = bg_alt },
    TelescopePreviewBorder  = { fg = v.border, bg = bg_alt },
    TelescopePreviewTitle   = { fg = v.bg, bg = s.cyan, bold = true },
    TelescopeTitle          = { fg = v.bg, bg = s.blue, bold = true },

    -- fzf-lua
    FzfLuaNormal            = { fg = v.fg, bg = bg_alt },
    FzfLuaBorder            = { fg = v.border, bg = bg_alt },
    FzfLuaTitle             = { fg = v.bg, bg = s.blue, bold = true },
    FzfLuaTitleFlags        = { fg = s.orange, bg = bg_alt },
    FzfLuaBackdrop          = { bg = v.bg },
    FzfLuaPreviewNormal     = { fg = v.fg, bg = bg_alt },
    FzfLuaPreviewBorder     = { fg = v.border, bg = bg_alt },
    FzfLuaPreviewTitle      = { fg = v.bg, bg = s.cyan, bold = true },
    FzfLuaCursor            = { fg = v.bg, bg = v.cursor },
    FzfLuaCursorLine        = { bg = v.bg_sel },
    FzfLuaCursorLineNr      = { fg = s.yellow, bg = v.bg_sel, bold = true },
    FzfLuaSearch            = { fg = v.bg, bg = s.yellow },
    FzfLuaScrollBorderEmpty = { fg = v.border, bg = bg_alt },
    FzfLuaScrollBorderFull  = { fg = s.blue, bg = bg_alt },
    FzfLuaScrollFloatEmpty  = { fg = v.border, bg = bg_alt },
    FzfLuaScrollFloatFull   = { fg = s.blue, bg = bg_alt },
    FzfLuaHelpNormal        = { fg = v.fg, bg = bg_alt },
    FzfLuaHelpBorder        = { fg = v.border, bg = bg_alt },
    FzfLuaHeaderBind        = { fg = s.magenta },
    FzfLuaHeaderText        = { fg = s.orange },
    FzfLuaPathColNr         = { fg = s.cyan },
    FzfLuaPathLineNr        = { fg = s.green },
    FzfLuaBufName           = { fg = s.magenta },
    FzfLuaBufNr             = { fg = s.yellow },
    FzfLuaBufFlagCur        = { fg = s.red },
    FzfLuaBufFlagAlt        = { fg = s.blue },
    FzfLuaTabTitle          = { fg = s.blue, bold = true },
    FzfLuaTabMarker         = { fg = s.yellow, bold = true },
    FzfLuaDirPart           = { fg = v.fg_dim },
    FzfLuaFilePart          = { fg = v.fg },
    FzfLuaLivePrompt        = { fg = s.red, bold = true },
    FzfLuaLiveSym           = { fg = s.red, bold = true },
    FzfLuaFzfNormal         = { fg = v.fg, bg = bg_alt },
    FzfLuaFzfCursorLine     = { bg = v.bg_sel },
    FzfLuaFzfMatch          = { fg = s.orange, bold = true },
    FzfLuaFzfBorder         = { fg = v.border, bg = bg_alt },
    FzfLuaFzfScrollbar      = { fg = s.blue, bg = bg_alt },
    FzfLuaFzfSeparator      = { fg = v.border, bg = bg_alt },
    FzfLuaFzfGutter         = { bg = bg_alt },
    FzfLuaFzfHeader         = { fg = s.orange, bg = bg_alt },
    FzfLuaFzfInfo           = { fg = v.fg_dim, bg = bg_alt },
    FzfLuaFzfPointer        = { fg = s.red, bg = bg_alt },
    FzfLuaFzfMarker         = { fg = s.yellow, bg = bg_alt },
    FzfLuaFzfSpinner        = { fg = s.yellow, bg = bg_alt },
    FzfLuaFzfPrompt         = { fg = s.blue, bg = bg_alt },
    FzfLuaFzfQuery          = { fg = v.fg, bg = bg_alt },

    -- bufferline.nvim
    BufferLineFill                       = { bg = v.bg_alt },
    BufferLineBackground                 = { fg = v.fg_dim, bg = v.bg_alt },
    BufferLineBufferVisible              = { fg = v.fg_dim, bg = v.bg_alt },
    BufferLineBufferSelected             = { fg = v.fg, bg = bg, bold = true, italic = false },
    BufferLineTab                        = { fg = v.fg_dim, bg = v.bg_alt },
    BufferLineTabSelected                = { fg = s.blue, bg = bg, bold = true },
    BufferLineTabSeparator               = { fg = v.bg_alt, bg = v.bg_alt },
    BufferLineTabSeparatorSelected       = { fg = v.bg_alt, bg = bg },
    BufferLineTabClose                   = { fg = s.red, bg = v.bg_alt },
    BufferLineCloseButton                = { fg = v.fg_dim, bg = v.bg_alt },
    BufferLineCloseButtonVisible         = { fg = v.fg_dim, bg = v.bg_alt },
    BufferLineCloseButtonSelected        = { fg = s.red, bg = bg },
    BufferLineSeparator                  = { fg = v.bg_alt, bg = v.bg_alt },
    BufferLineSeparatorVisible           = { fg = v.bg_alt, bg = v.bg_alt },
    BufferLineSeparatorSelected          = { fg = v.bg_alt, bg = bg },
    BufferLineOffsetSeparator            = { fg = v.border, bg = v.bg_alt },
    BufferLineIndicatorVisible           = { fg = v.bg_alt, bg = v.bg_alt },
    BufferLineIndicatorSelected          = { fg = s.blue, bg = bg },
    BufferLineModified                   = { fg = s.yellow, bg = v.bg_alt },
    BufferLineModifiedVisible            = { fg = s.yellow, bg = v.bg_alt },
    BufferLineModifiedSelected           = { fg = s.yellow, bg = bg },
    BufferLineDuplicate                  = { fg = v.fg_dim, bg = v.bg_alt, italic = true },
    BufferLineDuplicateVisible           = { fg = v.fg_dim, bg = v.bg_alt, italic = true },
    BufferLineDuplicateSelected          = { fg = v.fg_dim, bg = bg, italic = true },
    BufferLinePick                       = { fg = s.red, bg = v.bg_alt, bold = true, italic = true },
    BufferLinePickVisible                = { fg = s.red, bg = v.bg_alt, bold = true, italic = true },
    BufferLinePickSelected               = { fg = s.red, bg = bg, bold = true, italic = true },
    BufferLineNumbers                    = { fg = v.fg_dim, bg = v.bg_alt },
    BufferLineNumbersVisible             = { fg = v.fg_dim, bg = v.bg_alt },
    BufferLineNumbersSelected            = { fg = v.fg, bg = bg, bold = true },
    BufferLineDiagnostic                 = { fg = v.fg_dim, bg = v.bg_alt },
    BufferLineDiagnosticVisible          = { fg = v.fg_dim, bg = v.bg_alt },
    BufferLineDiagnosticSelected         = { fg = v.fg, bg = bg, bold = true, italic = true },
    BufferLineError                      = { fg = s.red, bg = v.bg_alt },
    BufferLineErrorVisible               = { fg = s.red, bg = v.bg_alt },
    BufferLineErrorSelected              = { fg = s.red, bg = bg, bold = true, italic = true },
    BufferLineErrorDiagnostic            = { fg = s.red, bg = v.bg_alt },
    BufferLineErrorDiagnosticVisible     = { fg = s.red, bg = v.bg_alt },
    BufferLineErrorDiagnosticSelected    = { fg = s.red, bg = bg, bold = true, italic = true },
    BufferLineWarning                    = { fg = s.yellow, bg = v.bg_alt },
    BufferLineWarningVisible             = { fg = s.yellow, bg = v.bg_alt },
    BufferLineWarningSelected            = { fg = s.yellow, bg = bg, bold = true, italic = true },
    BufferLineWarningDiagnostic          = { fg = s.yellow, bg = v.bg_alt },
    BufferLineWarningDiagnosticVisible   = { fg = s.yellow, bg = v.bg_alt },
    BufferLineWarningDiagnosticSelected  = { fg = s.yellow, bg = bg, bold = true, italic = true },
    BufferLineInfo                       = { fg = s.blue, bg = v.bg_alt },
    BufferLineInfoVisible                = { fg = s.blue, bg = v.bg_alt },
    BufferLineInfoSelected               = { fg = s.blue, bg = bg, bold = true, italic = true },
    BufferLineInfoDiagnostic             = { fg = s.blue, bg = v.bg_alt },
    BufferLineInfoDiagnosticVisible      = { fg = s.blue, bg = v.bg_alt },
    BufferLineInfoDiagnosticSelected     = { fg = s.blue, bg = bg, bold = true, italic = true },
    BufferLineHint                       = { fg = s.cyan, bg = v.bg_alt },
    BufferLineHintVisible                = { fg = s.cyan, bg = v.bg_alt },
    BufferLineHintSelected               = { fg = s.cyan, bg = bg, bold = true, italic = true },
    BufferLineHintDiagnostic             = { fg = s.cyan, bg = v.bg_alt },
    BufferLineHintDiagnosticVisible      = { fg = s.cyan, bg = v.bg_alt },
    BufferLineHintDiagnosticSelected     = { fg = s.cyan, bg = bg, bold = true, italic = true },
    BufferLineGroupSeparator             = { fg = v.border, bg = v.bg_alt },
    BufferLineGroupLabel                 = { fg = v.bg, bg = s.blue, bold = true },

    NeoTreeNormal        = { fg = v.fg, bg = bg_alt },
    NeoTreeNormalNC      = { fg = v.fg, bg = bg_alt },
    NeoTreeDirectoryIcon = { fg = s.blue },
    NeoTreeGitModified   = { fg = s.yellow },
    NeoTreeGitAdded      = { fg = s.green },
    NeoTreeGitDeleted    = { fg = s.red },

    -- snacks.nvim picker (LazyVim default)
    SnacksPicker              = { fg = v.fg, bg = bg_alt },
    SnacksPickerBorder        = { fg = v.border, bg = bg_alt },
    SnacksPickerTitle         = { fg = v.bg, bg = s.blue, bold = true },
    SnacksPickerFooter        = { fg = v.fg_dim, bg = bg_alt },
    SnacksPickerPrompt        = { fg = s.blue, bg = bg_alt, bold = true },
    SnacksPickerInput         = { fg = v.fg, bg = bg_alt },
    SnacksPickerInputBorder   = { fg = s.blue, bg = bg_alt },
    SnacksPickerInputTitle    = { fg = v.bg, bg = s.blue, bold = true },
    SnacksPickerList          = { fg = v.fg, bg = bg_alt },
    SnacksPickerListBorder    = { fg = v.border, bg = bg_alt },
    SnacksPickerListTitle     = { fg = v.bg, bg = s.violet, bold = true },
    SnacksPickerListCursorLine = { bg = v.bg_sel, bold = true },
    SnacksPickerPreview       = { fg = v.fg, bg = bg_alt },
    SnacksPickerPreviewBorder = { fg = v.border, bg = bg_alt },
    SnacksPickerPreviewTitle  = { fg = v.bg, bg = s.cyan, bold = true },
    SnacksPickerMatch         = { fg = s.orange, bold = true },
    SnacksPickerSelected      = { fg = s.yellow, bold = true },
    SnacksPickerDir           = { fg = v.fg_dim },
    SnacksPickerFile          = { fg = v.fg },
    SnacksPickerPathHidden    = { fg = v.fg_dim, italic = true },
    SnacksPickerPathIgnored   = { fg = v.fg_dim, italic = true },
    SnacksPickerKeymapLhs     = { fg = s.magenta },
    SnacksPickerKeymapRhs     = { fg = v.fg_dim },
    SnacksPickerIconDirectory = { fg = s.blue },
    SnacksPickerIconFile      = { fg = v.fg },
    SnacksPickerGitStatus     = { fg = s.yellow },
    SnacksPickerGitStatusAdded    = { fg = s.green },
    SnacksPickerGitStatusModified = { fg = s.yellow },
    SnacksPickerGitStatusDeleted  = { fg = s.red },
    SnacksPickerGitStatusRenamed  = { fg = s.blue },
    SnacksPickerGitStatusUntracked = { fg = v.fg_dim },
    SnacksPickerBufFlags      = { fg = s.violet },
    SnacksPickerRow           = { fg = s.cyan },
    SnacksPickerCol           = { fg = s.cyan },
    SnacksPickerDelim         = { fg = v.fg_dim },
    SnacksPickerSpecial       = { fg = s.orange },
    SnacksPickerTotals        = { fg = v.fg_dim, italic = true },
    SnacksPickerCursorLine    = { bg = v.bg_sel },

    -- snacks dashboard / common
    SnacksNormal       = { fg = v.fg, bg = bg_alt },
    SnacksNormalNC     = { fg = v.fg, bg = bg_alt },
    SnacksWinBar       = { fg = v.fg, bg = bg_alt },
    SnacksWinBarNC     = { fg = v.fg_dim, bg = bg_alt },
    SnacksDashboardHeader = { fg = s.orange, bold = true },
    SnacksDashboardIcon   = { fg = s.blue },
    SnacksDashboardKey    = { fg = s.magenta },
    SnacksDashboardDesc   = { fg = v.fg },
    SnacksDashboardFooter = { fg = v.fg_dim, italic = true },
  }

  return hl
end

return M
